<?php

namespace App\Tests\Unit\Repository;

use App\Repository\BookRepository;
use PHPUnit\Framework\TestCase;

class BookRepositoryTest extends TestCase
{
    private BookRepository $bookRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}